# coding: utf-8

"""
    weather.gov API

    weather.gov API  # noqa: E501

    OpenAPI spec version: 1.8.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AlertAtomFeed(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'generator': 'str',
        'updated': 'str',
        'author': 'AlertAtomFeedAuthor',
        'title': 'str',
        'entry': 'list[AlertAtomEntry]'
    }

    attribute_map = {
        'id': 'id',
        'generator': 'generator',
        'updated': 'updated',
        'author': 'author',
        'title': 'title',
        'entry': 'entry'
    }

    def __init__(self, id=None, generator=None, updated=None, author=None, title=None, entry=None):  # noqa: E501
        """AlertAtomFeed - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._generator = None
        self._updated = None
        self._author = None
        self._title = None
        self._entry = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if generator is not None:
            self.generator = generator
        if updated is not None:
            self.updated = updated
        if author is not None:
            self.author = author
        if title is not None:
            self.title = title
        if entry is not None:
            self.entry = entry

    @property
    def id(self):
        """Gets the id of this AlertAtomFeed.  # noqa: E501


        :return: The id of this AlertAtomFeed.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AlertAtomFeed.


        :param id: The id of this AlertAtomFeed.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def generator(self):
        """Gets the generator of this AlertAtomFeed.  # noqa: E501


        :return: The generator of this AlertAtomFeed.  # noqa: E501
        :rtype: str
        """
        return self._generator

    @generator.setter
    def generator(self, generator):
        """Sets the generator of this AlertAtomFeed.


        :param generator: The generator of this AlertAtomFeed.  # noqa: E501
        :type: str
        """

        self._generator = generator

    @property
    def updated(self):
        """Gets the updated of this AlertAtomFeed.  # noqa: E501


        :return: The updated of this AlertAtomFeed.  # noqa: E501
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this AlertAtomFeed.


        :param updated: The updated of this AlertAtomFeed.  # noqa: E501
        :type: str
        """

        self._updated = updated

    @property
    def author(self):
        """Gets the author of this AlertAtomFeed.  # noqa: E501


        :return: The author of this AlertAtomFeed.  # noqa: E501
        :rtype: AlertAtomFeedAuthor
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this AlertAtomFeed.


        :param author: The author of this AlertAtomFeed.  # noqa: E501
        :type: AlertAtomFeedAuthor
        """

        self._author = author

    @property
    def title(self):
        """Gets the title of this AlertAtomFeed.  # noqa: E501


        :return: The title of this AlertAtomFeed.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this AlertAtomFeed.


        :param title: The title of this AlertAtomFeed.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def entry(self):
        """Gets the entry of this AlertAtomFeed.  # noqa: E501


        :return: The entry of this AlertAtomFeed.  # noqa: E501
        :rtype: list[AlertAtomEntry]
        """
        return self._entry

    @entry.setter
    def entry(self, entry):
        """Sets the entry of this AlertAtomFeed.


        :param entry: The entry of this AlertAtomFeed.  # noqa: E501
        :type: list[AlertAtomEntry]
        """

        self._entry = entry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlertAtomFeed, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertAtomFeed):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
