# coding: utf-8

"""
    weather.gov API

    weather.gov API  # noqa: E501

    OpenAPI spec version: 1.8.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AlertReferences(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'identifier': 'AlertId',
        'sender': 'str',
        'sent': 'datetime'
    }

    attribute_map = {
        'id': '@id',
        'identifier': 'identifier',
        'sender': 'sender',
        'sent': 'sent'
    }

    def __init__(self, id=None, identifier=None, sender=None, sent=None):  # noqa: E501
        """AlertReferences - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._identifier = None
        self._sender = None
        self._sent = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if identifier is not None:
            self.identifier = identifier
        if sender is not None:
            self.sender = sender
        if sent is not None:
            self.sent = sent

    @property
    def id(self):
        """Gets the id of this AlertReferences.  # noqa: E501

        An API link to the prior alert.  # noqa: E501

        :return: The id of this AlertReferences.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AlertReferences.

        An API link to the prior alert.  # noqa: E501

        :param id: The id of this AlertReferences.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def identifier(self):
        """Gets the identifier of this AlertReferences.  # noqa: E501


        :return: The identifier of this AlertReferences.  # noqa: E501
        :rtype: AlertId
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this AlertReferences.


        :param identifier: The identifier of this AlertReferences.  # noqa: E501
        :type: AlertId
        """

        self._identifier = identifier

    @property
    def sender(self):
        """Gets the sender of this AlertReferences.  # noqa: E501

        The sender of the prior alert.  # noqa: E501

        :return: The sender of this AlertReferences.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this AlertReferences.

        The sender of the prior alert.  # noqa: E501

        :param sender: The sender of this AlertReferences.  # noqa: E501
        :type: str
        """

        self._sender = sender

    @property
    def sent(self):
        """Gets the sent of this AlertReferences.  # noqa: E501

        The time the prior alert was sent.  # noqa: E501

        :return: The sent of this AlertReferences.  # noqa: E501
        :rtype: datetime
        """
        return self._sent

    @sent.setter
    def sent(self, sent):
        """Sets the sent of this AlertReferences.

        The time the prior alert was sent.  # noqa: E501

        :param sent: The sent of this AlertReferences.  # noqa: E501
        :type: datetime
        """

        self._sent = sent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlertReferences, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertReferences):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
