# coding: utf-8

"""
    weather.gov API

    weather.gov API  # noqa: E501

    OpenAPI spec version: 1.8.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GridpointQuantitativeValueLayer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uom': 'UnitOfMeasure',
        'values': 'list[GridpointQuantitativeValueLayerValues]'
    }

    attribute_map = {
        'uom': 'uom',
        'values': 'values'
    }

    def __init__(self, uom=None, values=None):  # noqa: E501
        """GridpointQuantitativeValueLayer - a model defined in Swagger"""  # noqa: E501
        self._uom = None
        self._values = None
        self.discriminator = None
        if uom is not None:
            self.uom = uom
        self.values = values

    @property
    def uom(self):
        """Gets the uom of this GridpointQuantitativeValueLayer.  # noqa: E501


        :return: The uom of this GridpointQuantitativeValueLayer.  # noqa: E501
        :rtype: UnitOfMeasure
        """
        return self._uom

    @uom.setter
    def uom(self, uom):
        """Sets the uom of this GridpointQuantitativeValueLayer.


        :param uom: The uom of this GridpointQuantitativeValueLayer.  # noqa: E501
        :type: UnitOfMeasure
        """

        self._uom = uom

    @property
    def values(self):
        """Gets the values of this GridpointQuantitativeValueLayer.  # noqa: E501


        :return: The values of this GridpointQuantitativeValueLayer.  # noqa: E501
        :rtype: list[GridpointQuantitativeValueLayerValues]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this GridpointQuantitativeValueLayer.


        :param values: The values of this GridpointQuantitativeValueLayer.  # noqa: E501
        :type: list[GridpointQuantitativeValueLayerValues]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GridpointQuantitativeValueLayer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GridpointQuantitativeValueLayer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
