# coding: utf-8

"""
    weather.gov API

    weather.gov API  # noqa: E501

    OpenAPI spec version: 1.8.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.geo_json_feature import GeoJsonFeature  # noqa: F401,E501

class ObservationStationGeoJson(GeoJsonFeature):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'properties': 'ObservationStation'
    }
    if hasattr(GeoJsonFeature, "swagger_types"):
        swagger_types.update(GeoJsonFeature.swagger_types)

    attribute_map = {
        'properties': 'properties'
    }
    if hasattr(GeoJsonFeature, "attribute_map"):
        attribute_map.update(GeoJsonFeature.attribute_map)

    def __init__(self, properties=None, *args, **kwargs):  # noqa: E501
        """ObservationStationGeoJson - a model defined in Swagger"""  # noqa: E501
        self._properties = None
        self.discriminator = None
        if properties is not None:
            self.properties = properties
        GeoJsonFeature.__init__(self, *args, properties=properties, **kwargs)

    @property
    def properties(self):
        """Gets the properties of this ObservationStationGeoJson.  # noqa: E501


        :return: The properties of this ObservationStationGeoJson.  # noqa: E501
        :rtype: ObservationStation
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this ObservationStationGeoJson.


        :param properties: The properties of this ObservationStationGeoJson.  # noqa: E501
        :type: ObservationStation
        """

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ObservationStationGeoJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObservationStationGeoJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
