# coding: utf-8

"""
    weather.gov API

    weather.gov API  # noqa: E501

    OpenAPI spec version: 1.8.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ObservationCloudLayers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base': 'QuantitativeValue',
        'amount': 'MetarSkyCoverage'
    }

    attribute_map = {
        'base': 'base',
        'amount': 'amount'
    }

    def __init__(self, base=None, amount=None):  # noqa: E501
        """ObservationCloudLayers - a model defined in Swagger"""  # noqa: E501
        self._base = None
        self._amount = None
        self.discriminator = None
        self.base = base
        self.amount = amount

    @property
    def base(self):
        """Gets the base of this ObservationCloudLayers.  # noqa: E501


        :return: The base of this ObservationCloudLayers.  # noqa: E501
        :rtype: QuantitativeValue
        """
        return self._base

    @base.setter
    def base(self, base):
        """Sets the base of this ObservationCloudLayers.


        :param base: The base of this ObservationCloudLayers.  # noqa: E501
        :type: QuantitativeValue
        """
        if base is None:
            raise ValueError("Invalid value for `base`, must not be `None`")  # noqa: E501

        self._base = base

    @property
    def amount(self):
        """Gets the amount of this ObservationCloudLayers.  # noqa: E501


        :return: The amount of this ObservationCloudLayers.  # noqa: E501
        :rtype: MetarSkyCoverage
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ObservationCloudLayers.


        :param amount: The amount of this ObservationCloudLayers.  # noqa: E501
        :type: MetarSkyCoverage
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ObservationCloudLayers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObservationCloudLayers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
