# coding: utf-8

"""
    weather.gov API

    weather.gov API  # noqa: E501

    OpenAPI spec version: 1.8.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ZoneForecastPeriods(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'number': 'int',
        'name': 'str',
        'detailed_forecast': 'str'
    }

    attribute_map = {
        'number': 'number',
        'name': 'name',
        'detailed_forecast': 'detailedForecast'
    }

    def __init__(self, number=None, name=None, detailed_forecast=None):  # noqa: E501
        """ZoneForecastPeriods - a model defined in Swagger"""  # noqa: E501
        self._number = None
        self._name = None
        self._detailed_forecast = None
        self.discriminator = None
        self.number = number
        self.name = name
        self.detailed_forecast = detailed_forecast

    @property
    def number(self):
        """Gets the number of this ZoneForecastPeriods.  # noqa: E501

        A sequential identifier number.  # noqa: E501

        :return: The number of this ZoneForecastPeriods.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this ZoneForecastPeriods.

        A sequential identifier number.  # noqa: E501

        :param number: The number of this ZoneForecastPeriods.  # noqa: E501
        :type: int
        """
        if number is None:
            raise ValueError("Invalid value for `number`, must not be `None`")  # noqa: E501

        self._number = number

    @property
    def name(self):
        """Gets the name of this ZoneForecastPeriods.  # noqa: E501

        A textual description of the period.  # noqa: E501

        :return: The name of this ZoneForecastPeriods.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ZoneForecastPeriods.

        A textual description of the period.  # noqa: E501

        :param name: The name of this ZoneForecastPeriods.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def detailed_forecast(self):
        """Gets the detailed_forecast of this ZoneForecastPeriods.  # noqa: E501

        A detailed textual forecast for the period.  # noqa: E501

        :return: The detailed_forecast of this ZoneForecastPeriods.  # noqa: E501
        :rtype: str
        """
        return self._detailed_forecast

    @detailed_forecast.setter
    def detailed_forecast(self, detailed_forecast):
        """Sets the detailed_forecast of this ZoneForecastPeriods.

        A detailed textual forecast for the period.  # noqa: E501

        :param detailed_forecast: The detailed_forecast of this ZoneForecastPeriods.  # noqa: E501
        :type: str
        """
        if detailed_forecast is None:
            raise ValueError("Invalid value for `detailed_forecast`, must not be `None`")  # noqa: E501

        self._detailed_forecast = detailed_forecast

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ZoneForecastPeriods, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZoneForecastPeriods):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
